"""Write the airfoil data module for the web app and a Python reference file for the JS tests."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
for p in (ROOT, ROOT / "src"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

import numpy as np  # noqa: E402

import config as cfg  # noqa: E402
import airfoil_data  # noqa: E402
import design_space as ds  # noqa: E402

WEB_JS = ROOT / "docs" / "js" / "airfoilData.js"
REFERENCE = ROOT / "tests" / "js_reference.json"
POLAR_STEP = 0.5   # deg, thinned polar grid for the web page


def polar_thinned(fname):
    a, cl, cd = airfoil_data.load_polar(airfoil_data.find_file(fname))
    cm = np.loadtxt(airfoil_data.find_file(fname), skiprows=11, usecols=(4,))
    order = np.argsort(a)
    a, cl, cd, cm = a[order], cl[order], cd[order], cm[order]
    grid = np.arange(-12, 18 + 1e-9, POLAR_STEP)
    inside = (grid >= a.min()) & (grid <= a.max())
    return grid[inside], np.interp(grid[inside], a, cl), np.interp(grid[inside], a, cd), np.interp(grid[inside], a, cm)


def main():
    rows = airfoil_data.summarize()
    data = {}
    for name, r in rows.items():
        fname = cfg.AIRFOILS[name][0]
        a, cl, cd, cm = polar_thinned(fname)
        data[name] = dict(
            clmax=round(float(r["clmax"]), 5), aStall=float(r["a_stall"]), aL0=round(float(r["aL0"]), 4),
            tc=round(float(r["tc"]), 5), aL0Method=cfg.AIRFOILS[name][1],
            polar=dict(alpha=[round(float(v), 2) for v in a], cl=[round(float(v), 4) for v in cl],
                       cd=[round(float(v), 5) for v in cd], cm=[round(float(v), 4) for v in cm]))
    WEB_JS.parent.mkdir(parents=True, exist_ok=True)
    WEB_JS.write_text("// Generated by scripts/export_web_data.py from the Re = 300,000 XFLR5 polars. Do not edit.\n"
                      "export const AIRFOILS = " + json.dumps(data, indent=1) + ";\n", encoding="utf8")

    ref = {"best": {}, "points": []}
    for name, af in rows.items():
        ARs, lams = ds.grids(af)
        best, ok = ds.pick_best(ds.scan(af, ARs, lams))
        ref["best"][name] = _dump(best, ok)
    probes = [("S7062", 10.0, 0.5), ("S7062", 12.0, 1.0), ("NACA 2415", 8.0, 0.7), ("S1223", 14.0, 0.4),
              ("HW4 (PACTM iter3)", 9.0, 0.6), ("NACA 64-212", 6.0, 0.35)]
    for name, AR, lam in probes:
        r = ds.evaluate(rows[name], AR, lam)
        ref["points"].append(dict(airfoil=name, **_dump(r, r["feasible"])))
    REFERENCE.write_text(json.dumps(ref, indent=1), encoding="utf8")
    print(f"wrote {WEB_JS} and {REFERENCE}")


def _dump(r, ok):
    sec = r["spar"]
    return dict(AR=float(r["AR"]), lam=float(r["lam"]), S=float(r["S"]), b=float(r["b"]),
                CL_cruise=float(r["CL_cruise"]), alpha_cruise=float(r["alpha_cruise"]),
                alpha_land=float(r["alpha_land"]), land_ratio=float(r["land_ratio"]),
                a_w=float(r["a_w"]), e=float(r["e"]), CD0=float(r["CD0"]), CDi=float(r["CDi"]),
                LD=float(r["LD"]), I_req=float(r["I_req"]), M_root=float(r["M_root"]),
                delta_pct=float(r["delta_pct"]), spar_kind=sec["kind"],
                spar_w=float(sec.get("w", 0)), spar_h=float(sec.get("h", 0)), spar_d=float(sec.get("d", 0)),
                sigma=float(sec["sigma"]), fit_excess=float(sec["fit_excess"]), feasible=bool(ok),
                viol={k: float(v) for k, v in r["viol"].items()})


if __name__ == "__main__":
    main()
